### ISSUE TITLE
请问数据会放出来吗，谢谢

### ISSUE THREAD

**Issue by Mryangkaitong** [vaew/SkyScript-100M#1]

**Comment by vaew** [comment]
代码和数据会通过伦理/法律审查后尽快release😁

**Comment by Mryangkaitong** [comment]
> 代码和数据会通过伦理/法律审查后尽快release😁

非常感谢～～～

**Comment by ZhikangNiu** [comment]
请问数据包含音频吗？是否可以放一些demo数据展示下呢？ @vaew

**Comment by vaew** [comment]
最终release出来的的demo数据的内容我们内部也还在讨论+审核哈，我们的原始数据是包含音频和视频的

**Comment by 3DMM-ICME2025** [comment]
您好，很赞的工作，请问数据集还会公布不
